version: '3.1'

networks:
  network:
    name: ${PROJECT}

services:
  store:
    networks:
      - network
    build:
      context: .
      dockerfile: ../../common/docker/node-dev/dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - '.:/app'
    entrypoint: 'sh -c "npm i && npm start"'
    ports:
      - 8083:80