version: '3.8'

networks:
  ${PROJECT}:
    name: ${PROJECT}

services:
  docs:
    networks:
      - ${PROJECT}
    build:
      context: .
      dockerfile: ${PWD}/common/docker/node-dev.dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - '${PWD}/svc/docs:/app'
    environment:
      PORT: 80
      API_SERVICE_HOST: api
      API_SERVICE_PORT: 80
      PARSER_SERVICE_HOST: parser
      PARSER_SERVICE_PORT: 80
    working_dir: /app/svc/docs
    entrypoint: 'sh -c "npm install && npm run dev"'
    ports:
      - 9001:80