for i in glob(["*.dockerfile", "*.dockerignore"]):
    # log.error("{i}.dockerignore".format(i=i))
    # export_file(
    #     name="{i}.dockerignore".format(i=i),
    #     src="{i}.dockerignore".format(i=i),
    #     visibility=["PUBLIC"]
    # )

    export_file(
        name=i,
        src=i,
        visibility=["PUBLIC"]
    )
