version: '3.8'

networks:
  ${PROJECT}:
    name: ${PROJECT}

services:
  blogs:
    networks:
      - ${PROJECT}
    build:
      context: .
      dockerfile: ${PWD}/common/docker/dotnet-dev.dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - '${PWD}/svc/blogs:/app'
      - '${PWD}/svc/store/data:/app/static/store'
      - '/app/node_modules'
    environment:
      PORT: 80
      VITE_BLOGS_BASE_URL: http://blogs
    entrypoint: 'sh -c "dotnet watch run -p mrsauravsahu.api"'
    ports:
      - 8081:80
