version: '3.1'

networks:
  network:
    name: ${PROJECT}

services:
  blogs:
    networks:
      - network
    build:
      context: .
      dockerfile: ../../common/docker/dotnet-dev/dockerfile
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
    working_dir: /app/mrsauravsahu.api
    volumes:
      - '${PWD}/svc/blogs:/app'
    environment:
      Blogs__AppName: ${Blogs__AppName}
      Blogs__Version: ${Blogs__Version}
      Blogs__ContactEmail: ${MRSS__CONTACT_EMAIL}
      Blogs__StoreBasePath: "/app/store"
      Files__BasePath: "/app/store"
      Github__Token: ${Github__Token}
    entrypoint: 'sh -c "dotnet watch run"'
    ports:
      - 8082:80