version: '3.8'

networks:
  ${PROJECT}:
    name: ${PROJECT}

services:
  blogs:
    networks:
      - ${PROJECT}
    build:
      context: .
      dockerfile: ../../common/docker/dotnet-dev/dockerfile
      args: 
        DOTNET_VERSION: ${DOTNET_VERSION}
    working_dir: /app/mrsauravsahu.api
    volumes:
      - '${PWD}/svc/blogs:/app'
      - '${PWD}/svc/store:/app/store'
    entrypoint: 'sh -c "dotnet watch run"'
    environment:
      Blogs__AppName: $Blogs__AppName
      Blogs__Version: $Blogs__Version
      Blogs__ContactEmail: $MRSS__CONTACT_EMAIL
      Blogs__StoreBasePath: "/app/store"
      Files__BasePath: "/app/store"
      Github__Token: $Github__Token
    ports:
      - 8081:80