version: '3.8'

networks:
  ${PROJECT}:
    name: ${PROJECT}

services:
  store:
    networks:
      - ${PROJECT}
    build:
      context: .
      dockerfile: ${PWD}/common/docker/node-dev.dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - '${PWD}/apps/store:/app'
      - '/app/node_modules'
    environment:
      PORT: 80
    entrypoint: 'sh -c "npm install && npm start"'
    ports:
      - 3000:80
