apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mrsauravsahu
  name: blogs
  labels:
    app: blogs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blogs
  template:
    metadata:
      labels:
        app: blogs
    spec:
      containers:
        - name: main
          image: //svc/blogs:blogs
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 250m
              memory: 256Mi
            requests:
              cpu: 250m
              memory: 128Mi
          ports:
            - containerPort: 80