version: '3.1'

networks:
  network:
    name: ${PROJECT}

services:
  parser:
    networks:
      - network
    build:
      context: .
      dockerfile: ../../common/docker/dotnet-dev/dockerfile
      args:
        DOTNET_VERSION: ${DOTNET_VERSION}
    volumes:
      - '.:/app'
    entrypoint: 'sh -c "dotnet watch run"'
    ports:
      - 8081:80