version: '3.8'

networks:
  network:
    name: ${PROJECT}

services:
  api:
    build:
      context: .
      dockerfile: ${PWD}/common/docker/node-dev/dockerfile
      args:
        NODE_VERSION: ${NODE_VERSION}
    volumes:
      - '${PWD}/svc/api:/app'
    environment:
      PORT: 80
    entrypoint: 'sh -c "npm install && npm run start:dev"'
    ports:
      - 8080:80
