name: ci-parser-service

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/ci-parser-service.yml'
      - 'common/**'
      - 'svc/parser/**'

env:
  NODE_VERSION: 14.17.6
  SERVICE: parser

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - uses: sagikazarmark/setup-please-action@v0

      - name: Build Service
        run: plz build //svc/$SERVICE && plz run //svc/$SERVICE